name: Deploy to Server

on:
  push:
    branches:
      - action-test # 或你使用的部署分支

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
          echo "REMOTE_HOST"
          cat ~/.ssh/known_hosts
          echo "id_rsa"
          cat ~/.ssh/id_rsa

      - name: Run deployment commands
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            mkdir -p {{ secrets.DEPLOY_PATH }}
            cd ${{ secrets.DEPLOY_PATH }}
            git clone https://github.com/lvzero535/idux-components.git .
          EOF
